### ISSUE TITLE
Images aren't loading on the newest Version

### ISSUE THREAD

**Issue by strich3** [Mr2u/fosscord-server#3]
So basically images worked yesterday. Then i updated it and now images just won't load (Emotes, server icons and other stuff)

Hope it's ok to create an issue. It's just a bug i noticed :)

**Comment by MaddyUnderStars** [comment]
Oh damn why didn't I get an email for this. Does this still occur? Is it all images/etc, such as attachments, avatars, banners, as well as images from other sites? I don't remember making any changes to the cdn code a week ago, but I'll check again in the morning tomorrow. In any case, this is most likely a configuration issue on your end, because it is functional on the official slowcord instance.

**Comment by strich3** [comment]
Ah yeah, i forgot abt this. On the newer Versions weren‘t any icons (User, Server or any images). But this only occurred on the first launch. Idk, but it works now

**Comment by MaddyUnderStars** [comment]
Ah ok, cool. Sorry for the wait, glad it resolved itself

**Comment by strich3** [comment]
![image](https://user-images.githubusercontent.com/56207893/202921545-e57645ce-fb49-4923-972a-c56f61f0856a.png)

**Comment by strich3** [comment]
The error is here once again
